version: '3.3'

services:
  maven:
    image: maven:3.9.7-sapmachine-22
    working_dir: /home/maven
    volumes:
      - ./SIAula07:/home/maven  # Copia a pasta SIAula07 para dentro do /home/maven
      - maven-out:/home/maven/SIAula07/target  # Novo volume para saída do Maven
    command: mvn package
    depends_on:
      - db

  app:
    image: tomcat:9.0
    container_name: jsp_app
    volumes:
      - maven-out:/usr/local/tomcat/webapps/ROOT.war  # Mapeia o volume de saída do Maven
      - ./logs:/usr/local/tomcat/logs  # Novo volume para logs do Tomcat
    ports:
      - 80:8080
    depends_on:
      - db
      - maven
    environment:
      - JAVA_OPTS=-Dspring.datasource.url=jdbc:mysql://db:3306/aluguelchromebook -Dspring.datasource.username=root -Dspring.datasource.password=

  db:
    image: mysql:8.0
    restart: always
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: aluguelchromebook
      MYSQL_USER: teste
      MYSQL_PASSWORD: rootpassword
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./banco/modeloFisico/aluguelchromebook.sql:/docker-entrypoint-initdb.d/aluguelchromebook.sql

volumes:
  maven-out:
  db_data:
  logs:
